import "@/app/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ThemeToggle";
import GradientBackground from "@/components/GradientBackground";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <GradientBackground>
            <div className="flex min-h-screen flex-col">
              <header className="p-4 absolute top-0 right-0 z-10">
                <ModeToggle />
              </header>
              <main className="flex-1">
                {children} {/* Remove TRPCReactProvider wrapper */}
              </main>
            </div>
          </GradientBackground>
        </ThemeProvider>
      </body>
    </html>
  );
}